name: Workflow de Commits

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test || echo "Nenhum teste configurado, workflow continua"
